name: Update Version

on:
  push:
    branches:
      - main 

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Increase patch version
      run: |
        VERSION_FILE="version.txt"
        CURRENT_VERSION=$(cat $VERSION_FILE)
        IFS='.' read -r major minor patch <<< "$CURRENT_VERSION"
        NEW_PATCH=$((patch + 1))
        NEW_VERSION="$major.$minor.$NEW_PATCH"
        echo "New version: $NEW_VERSION"
        echo $NEW_VERSION > $VERSION_FILE

    - name: Commit updated version
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add version.txt
        git commit -m "Update version to $NEW_VERSION"
        git push

