name: Actions with Docker Project

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      POM_VERSION: ${{ steps.extract_version.outputs.version }}

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Maven Version Bump Action
        id: bump
        uses: mickem/gh-action-bump-maven-version@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from pom.xml
        id: extract_version
        uses: PERES-Richard/maven-get-version-action@v3.0.0
        with:
          path: '.' 

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: yaafsome/java-maven-fork:${{ env.POM_VERSION }}
          build-args: |
            JAR_VERSION: ${{ env.POM_VERSION }}
