name: Java CI with Maven
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Version:
    runs-on: ubuntu-22.04

    steps:
    - name: Setup Maven Action
      uses: s4u/setup-maven-action@v1.7.0
      with:
        checkout-fetch-depth: 0
        java-version: 8
        java-distribution: temurin
        maven-version: 3.9.2

    - name: fetch last tags
      run: |
        git fetch --tags
        VERSION=$(git tag | sort -V | tail -n 1)
        echo "My Latest version: $VERSION"

    - name: Set jar version
      id: set_jar
      run: |
        VERSION_PARTS=(${VERSION//./ })
        MAJOR=${VERSION_PARTS[0]}
        MINOR=${VERSION_PARTS[1]}
        PATCH=${VERSION_PARTS[2]}
        NEW_PATCH_NUM=$((PATCH+1))
        NEW_VERSION="${MAJOR}.${MINOR}.${NEW_PATCH_NUM}"
        echo "THE new version: $NEW_VERSION"
        echo "new_version=$NEW_VERSION" >> $GITHUB_ENV
        mvn versions:set -DnewVersion=$NEW_VERSION 
        echo "new_version=$NEW_VERSION" >> $GITHUB_ENV
        mvn versions:set -DnewVersion=$NEW_VERSION


    - name: Tests
      run: |
        mvn test
