name: Java CI with Maven
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Version:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3


    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: fetch last tags
      run: |
        git fetch --tags
        VERSION=$(git tag | sort -V | tail -n 1)
        echo "My Latest version: $VERSION"

    - name: Set jar version
      id: set_jar
      run: |
        VERSION_PARTS=(${VERSION//./ })
        MAJOR=VERSION_PARTS[0]
        MINOR=VERSION_PARTS[1]
        PATCH=VERSION_PARTS[2]
        NEW_PATCH_NUM=$((PATCH+1))
        NEW_VERSION="{MAJOR}.${MINOR}.${NEW_PATCH_NUM}"
        echo "THE new version: $NEW_VERSION"
        echo "new_version=$NEW_VERSION" >> $GITHUB_ENV
        mvn versions:set -DnewVersion=${{ NEW_VERSION }}


    - name: Tests
      run: |
        mvn test
