name: Java CI with Maven
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Version:
    runs-on: ubuntu-22.04

    steps:
    - name: Setup Maven Action
      uses: s4u/setup-maven-action@v1.7.0
      with:
        checkout-fetch-depth: 0
        java-version: 8
        java-distribution: temurin
        maven-version: 3.9.2

    - name: fetch last tags and set version
      run: |
        git fetch --tags
        VERSION=$(git tag | sort -V | tail -n 1)
        echo "My Latest version: $VERSION"
        echo "Initial VERSION: $VERSION"
        VERSION_PARTS=(${VERSION//./ })
        echo "VERSION_PARTS: ${VERSION_PARTS[@]}"
        MAJOR=${VERSION_PARTS[0]}
        MINOR=${VERSION_PARTS[1]}
        PATCH=${VERSION_PARTS[2]}
        echo "MAJOR: $MAJOR, MINOR: $MINOR, PATCH: $PATCH"
        NEW_PATCH_NUM=$((PATCH+1))
        NEW_VERSION="${MAJOR}.${MINOR}.${NEW_PATCH_NUM}"
        echo "Constructed NEW_VERSION: $NEW_VERSION"
        echo "new_version=$NEW_VERSION" >> $GITHUB_ENV
        mvn versions:set -DnewVersion=$NEW_VERSION 
        echo "new_version=$NEW_VERSION" >> $GITHUB_ENV
        echo "Final new_version=$NEW_VERSION"
