name: Java CI with Maven
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Version:
    runs-on: ubuntu 24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: fetch last tags
      run: |
        VERSION=${git fetch --tags && git tag | sort -V | tail -n 1}
        echo "Latest version: $VERSION"
        git tag
    - name: Set jar version
      run: |
        VERSION_PARTS=(${VERSION//./ })
        MAJOR=VERSION_PARTS[0]
        MINOR=VERSION_PARTS[1]
        PATCH=VERSION_PARTS[2]
        mvn versions:set -DnewVersion=(PATCH + 1)

    - name: Tests
      run: |
        mvn test


