name: Java CI with Maven
on:
  push:
    branches: [ "master", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # Use GITHUB_TOKEN for authentication

    - name: Setup Maven Action
      uses: s4u/setup-maven-action@v1.7.0
      with:
        checkout-fetch-depth: 0
        java-version: 8
        java-distribution: temurin
        maven-version: 3.9.2

    - name: Fetch last tags and set version
      id: version
      run: |
        git fetch --tags
        VERSION=$(git tag | sort -V | tail -n 1)
        echo "My Latest version: $VERSION"
        
        VERSION_PARTS=(${VERSION//./ })
        MAJOR=${VERSION_PARTS[0]}
        MINOR=${VERSION_PARTS[1]}
        PATCH=${VERSION_PARTS[2]}
        
        NEW_PATCH_NUM=$((PATCH + 1))
        NEW_VERSION="${MAJOR}.${MINOR}.${NEW_PATCH_NUM}"
        
        # Set the new version in Maven
        mvn versions:set -DnewVersion=$NEW_VERSION
        
        # Set the new version in GITHUB_ENV for future steps
        echo "new_version=$NEW_VERSION" >> $GITHUB_ENV
        
        # Set the output for GitHub Actions steps
        echo "::set-output name=new_version::$NEW_VERSION"
        
        echo "Final new_version=$NEW_VERSION"

    - name: Push new tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub token for git push
      run: |
        # Retrieve the new version from the environment
        NEW_TAG=${{ env.new_version }}
        
        # Create the tag
        git tag $NEW_TAG
        
        # Push the new tag to the repository
        git push origin $NEW_TAG

    - name: Check if the tag was pushed successfully
      run: |
        git fetch --tags
        # List all the tags
        git tag

        # Check if the new tag exists in the list of tags
        if git tag | grep -q "${{ env.new_version }}"; then
          echo "Tag ${{ env.new_version }} exists."
        else
          echo "Tag ${{ env.new_version }} was not created!" >&2
          exit 1
        fi

