name: Java CI with Maven

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "master" ]

jobs:
  version and build:
    runs-on: ubuntu 24.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: fetch last tags
      run: |
        VERSION=${git fetch --tags && git tag | sort -V | tail -n 1}
    - name: Set jar version
      run: |
        mvn versions:set -DnewVersion=($VERSION + 0.0.1)

    - name: Tests
      run: |
        mvn test


